# Generated by Django 3.2.9 on 2022-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'domain'), (1, 'discipline'), (2, 'sub-discipline'), (3, 'subject'), (4, 'topic'), (5, 'sub-topic')], default=0, verbose_name='level description')),
                ('materialized_paths', models.JSONField(default=list)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='topics.Topic')),
            ],
            options={
                'ordering': ['level', 'topic'],
            },
        ),
    ]
